source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NetworkManager-ObjC_Example' do
    pod "NetworkManager-ObjC", :path => "../"
end

target 'NetworkManager-ObjC_Tests' do
  pod "NetworkManager-ObjC", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
